# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# Build script for AERIS NS-3 module

def build(bld):
    module = bld.create_ns3_module('aeris', ['core', 'network', 'internet', 'mobility', 'energy', 'lr-wpan'])
    module.source = [
        'model/aeris-protocol.cc',
        'helper/aeris-helper.cc',
    ]

    module_test = bld.create_ns3_module_test_library('aeris')
    module_test.source = [
        'test/aeris-test-suite.cc',
    ]

    headers = bld(features='ns3header')
    headers.module = 'aeris'
    headers.source = [
        'model/aeris-protocol.h',
        'helper/aeris-helper.h',
    ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

def configure(conf):
    conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
